services:
  web-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5000:3000"   # Host 5000 -> Container 3000
    networks:
      - my-web-app-net
    depends_on:
      - backend-app

  backend-app:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    depends_on:
      - mysql
    networks:
      - my-web-app-net

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Prashant2932
      MYSQL_DATABASE: userdata
    volumes:
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-web-app-net
    # Uncomment below if you want host access to MySQL
    # ports:
    #   - "3306:3306"

networks:
  my-web-app-net:
    driver: bridge
