services:
  web-app:
    build: ./client
    ports:
      - "5000:3000"   # Host 5000 -> Container 3000
    networks:
      - mern-net
    depends_on:
      - backend-app

  backend-app:
    build: ./server
    networks:
      - mern-net
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Prashant2932
      MYSQL_DATABASE: userdata
    volumes:
      - db_data:/var/lib/mysql      # persistent volume for MySQL data
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mern-net

networks:
  mern-net:
    driver: bridge

volumes:
  db_data:      
